[#SEPACreditTransfer]
== REST API
_SEPA Credit Transfer_ is a type of <<PaymentMethods_PaymentMode_OfflineBankTransfer, Offline Bank Transfer>>.

{payment-gateway} supports referenced and non-referenced _SEPA Credit Transfer_ options.

[#SEPACreditTransfer_PaymentModeCountriesandCurrencies]
=== Countries and Currencies
[width=75%,cols="1h,3",stripes=none]
|===
| Countries    | Please contact <<ContactUs, Merchant Support>> for Countries.
| Currencies   | Please contact <<ContactUs, Merchant Support>> for Currencies.
|===

[#SEPACreditTransfer_CommunicationFormats]
=== Communication Formats
This table illustrates how _SEPA Credit Transfer_ notifications are
encoded and which formats and methods can be used for requests and
responses.
[width=75%,stripes=none]
|===
.2+h| Requests/Responses   | Format  | XML
                            | Methods | POST
h| IPN Encodement        2+| Please follow the instructions given
at <<GeneralPlatformFeatures_IPN_NotificationExamples, Instant Payment Notification>> to set up IPN.
|===


[#SEPACreditTransfer_Transactions]
=== Transactions


[#SEPACreditTransfer_TransactionTypes]
==== Transaction Types

For <<Glossary_TransactionType, transaction type>> details which are not given here look
at <<AppendixB,  Transaction Types>>.

[%autowidth]
|===
| Transaction Type | Description | Link to the Samples

| authorization | Verifies payment details for structural validity and /
or generates a reference ID for the merchant (not mandatory). | 
| pending-credit | Transaction is processed in the {payment-gateway}.
| See <<SEPACreditTransfer_Samples_PendingCredit, samples>>.
| void-pending-credit | Voids a pending-credit. +
Only available when the <<SEPA_TransactionType_Void_Restrictions, restrictions>> are met.
| See <<SEPACreditTransfer_Samples_VoidPendingCredit, samples>>.
| credit | Transaction is processed by {payment-provider-name} Bank. |
| credit-return | The payment is returned by the consumer bank. See <<SEPA_ReturnCodes, Return Codes>>. |
|===

NOTE: Recurring Transactions are *not* supported for _SEPA Credit Transfer_.

NOTE: The transaction type within the request must be ``credit`` or
``pending-credit``. A ``credit`` will be transformed into a ``pending-credit`` by default.


[#SEPACreditTransfer_TransactionTypes_refund]
.refund

You can use _SEPA Credit Transfer_ to return funds to consumers. +
If you use it to refund a specific debit transaction, we recommend to include a
``parent-transaction-id`` (i.e. the ``transaction-id`` of the successful preceding debit) in the request in order to be able to match the refund to the original transaction.

[#SEPACreditTransfer_TransactionTypes_void]
.void

SEPA void can be used with both SEPA payment methods: _SEPA Credit Transfer_ and _SEPA Direct Debit._

[#SEPACreditTransfer_Transactions_ExecutionDate]
==== Execution Date

NOTE: This is the date on which the transfer will be executed. According to
SEPA regulations, it is required to be one (1) business day after it has
entered the banking system. This date is set by {payment-provider-name} during
processing and is not part of the request or the response.

[#SEPACreditTransfer_TestCredentials]
=== Test Credentials

[cols="30h, 70"]
|===
| URLs (Endpoints) |``\https://{rest-api-test-endpoint}``
| Merchant Account ID (MAID) | 59a01668-693b-49f0-8a1f-f3c1ba025d45
| Username | 16390-testing
| Password | 3!3013=D3fD8X7
| Secret Key | Please contact <<ContactUs, merchant support>> for complete test credentials.
|===

[#SEPACreditTransfer_Workflow]
=== Workflow

image::images/diagrams/sepa_credit-transfer.svg[SEPA Credit Transfer Workflow]

. The transaction type within the request must be ``credit`` or ``pending-credit``.
. If the request is successful, a response will be returned with status
_Success_. This response means that the transaction has entered the
{payment-gateway} successfully. The transaction itself is in a _pending_
status, waiting to be sent to you bank account.
. If the request is not successful, a response will be returned with
status _Failed_. *The response always contains a status code and a description.*
Please read this description carefully as it will help to
understand why the transaction request has failed and what needs to be
fixed in order to send a successful transaction request.
. Once the transaction has been successfully sent to and processed by
the bank, a new transaction with type ``credit`` will be created in status
_Success_. This process usually takes up to 2 business days. The
transaction will then be forwarded the Central Bank for processing.
. If the transaction has been rejected by your bank, a
``credit`` transaction on status _Failed_ will be created and the
transaction will not be sent to the Central Bank.
. You receive a notification of the ``credit`` transaction.
//-

NOTE: Although a transaction has been successfully processed by your bank, the transaction may still be reversed by the consumer's bank for reasons such as insufficient funds, account owner deceased, bank account closed, etc. In this case, a ``credit-return`` transaction will be created and matched to the original ``credit`` transaction to ensure the merchant
has a complete overview for his debtor management. +
Refer to the list of <<SEPA_ReturnCodes, SEPA Return Codes>> for a full list of ``credit-return`` reasons.

You can request the status of the transaction at any time by sending a "<<GeneralPlatformFeatures_RetrieveTransaction_TransactionID, Retrieve Transaction by Transaction ID>>".

[#SEPACreditTransfer_Fields]
=== Fields

The fields used for SEPA _Credit Transfer_ requests, responses and
notifications are the same as the REST API fields. Please refer to:
<<RestApi_Fields, REST API Fields>>.

Only the fields listed below have different properties.

The following elements are mandatory (M), optional (O) or conditional
\(C) in a req(uest)/res(ponse)/notification (IPN).

[%autowidth, cols="m,,,,,,a"]
|===
| Field | req | res | IPN | Datatype | Size | Description

| descriptor 
| O 
| O 
| O 
| String 
| 100 
| Description on the settlement of the account holder's account about a
transaction. +
For SEPA Credit Transfer transactions, it will be combined with the
Provider Transaction Reference ID and the merchant's static
descriptor and will appear on the consumer's bank account statement.

| payment-methods.payment-method-mame 
| M 
| M 
| M 
| String 
| 15 
| Enter the name of the payment method ``sepacredit``.

| api-id 
|   
|   
| M 
| api-id 
| 25 

| The API ID is always returned in the notification. For SEPA it is ``---``.

| bank-account.bic 
| O 
| O 
| O 
| String 
| 8 or 11 
| **B**ank **I**dentifier **C**ode of the bank of the consumer. In SEPA area where <<SEPA_Reporting_IbanOnly, IBAN Only>> is enabled, ``bic`` is an optional field.

| bank-account.iban 
| C 
| C 
| C 
| String 
| 34 
| **I**nternational **B**ank **A**ccount **N**umber of the consumer. +
Mandatory if you do not provide a ``parent-transaction-id``.

| provider-transaction-reference-id 
|   
| M 
| M 
| String 
| 10 
| This ID provides a reference for the complete end-to-end lifecycle of a SEPA Credit Transfer transaction. It is used as a reference within the banking system to ensure all transactions referencing each other (e.g. a credit and a debit-return) are matched and that the complete lifecycle of a payment is identifiable. {payment-provider-name} generates this ID for you.

| account-holder.last-name 
| M 
| M 
| M 
| String 
| 32 
| Last name of the consumer.
|===

[#SEPACreditTransfer_Samples]
=== Samples

For corresponding notification samples, go to <<GeneralPlatformFeatures_IPN_NotificationExamples, Notification Examples>>.

[#SEPACreditTransfer_Samples_PendingCredit]
==== pending-credit

[#SEPACreditTransfer_Samples_PendingCredit_Xml]
*XML*

.XML pending-credit Request (Successful)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/sepacredit_pending-credit_request_success.xml[]
----

.XML pending-credit Response (Successful)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/sepacredit_pending-credit_response_success.xml[]
----

.XML pending-credit Request (Failure)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/sepacredit_pending-credit_request_failure.xml[]
----

.XML pending-credit Response (Failure)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/sepacredit_pending-credit_response_failure.xml[]
----

[#SEPACreditTransfer_Samples_PendingCredit_Json]
*JSON*

.JSON pending-credit Request (Successful)

[source,json,subs=attributes+]
----
include::{root}/samples/json/SEPACreditTransferSamplesPendingCreditJson_JSON_PendingCreditRequestSuccessful.json[]
----

.JSON pending-credit Response (Successful)

[source,json,subs=attributes+]
----
include::{root}/samples/json/SEPACreditTransferSamplesPendingCreditJson_JSON_PendingCreditResponseSuccessful.json[]
----

[#SEPACreditTransfer_Samples_VoidPendingCredit]
==== void-pending-credit

[NOTE]
====
*void-pending-credit Restrictions*

void-pending-credit transactions can be sent until the transaction is
not sent to the bank.
====

*XML*

.XML void-pending-credit Request (Successful)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/sepacredit_void-pending-credit_request_success.xml[]
----

.XML void-pending-credit Response (Successful)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/sepacredit_void-pending-credit_response_success_8938d389.xml[]
----

.XML void-pending-credit Request (Failed)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/sepacredit_void-pending-credit_request_.xml[]
----

.XML void-pending-credit Response (Failed)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/sepacredit_void-pending-credit_response_.xml[]
----

//-
