[#CreditCard_TransactionTypes_Purchase]
== purchase

[#CreditCard_TransactionTypes_Purchase_Introduction]
=== Introduction

purchase transfers the transaction amount without preceding
reservation from the consumer directly to the merchant. With this
transaction type merchants collect the money immediately while selling
goods or providing a service to the consumers. Merchants use purchase
in most of the cases to process POS transactions. It is also used for
immediate online payments, such as software downloads.


[#CreditCard_TransactionTypes_Purchase_Introduction_RealLife]
.Real-Life Example

[#CreditCard_TransactionTypes_Purchase_Introduction_RealLife_SinglePayment]
*Single Payment*

For POS payments, purchase is used when consumers hire a taxi and pay
the taxi fare with their credit card. Or the consumers shop in a
department store or grocery store and pay at the check out using their
credit cards.

In an online shopping process, purchase is used when consumers
download software, a movie or audio files.

[#CreditCard_TransactionTypes_Purchase_AvailabilityRestrictions_Sequence]
.Sequence

A purchase can be a stand-alone transaction. It may be followed by a
void-purchase or a refund-purchase. A
refund-purchase may be followed by a void-refund-purchase.

image::images/diagrams/cc-purchase-flow.svg[purchase_sequence]

See details for <<CreditCard_TransactionTypes_VoidRefund, void and refund>>.


[#CreditCard_TransactionTypes_Purchase_SendingData]
=== Sending Data

We only list samples for requests and responses. Notifications follow
the general structure described in
<<GeneralPlatformFeatures_IPN_NotificationExamples, General Platform Features>>.

Are you using
<<CreditCard_TransactionTypes_RunningTestSamples, Postman>> to send the requests?

- If yes, you can use the samples as provided below (_Request Header_ and _Request Sample_).
- If no, replace ``{{$guid}}`` with a globally unique ID in ``<request-id>``.

//-

[#CreditCard_TransactionTypes_Purchase_SendingData_StatusCodes]
.Status Codes

In ``<statuses>`` of the response you will find a number that represents a
<<StatusCodes, status code>>.

[#CreditCard_TransactionTypes_Purchase_SendingData_PurchaseUsingCardData]
.purchase Using Card Data

*Request*

If the credit card is used for the first time, the purchase request
will contain the explicit card data. The first response immediately
replaces the explicit card data with a token. The token will be used
from then on.

Read how a
<<CreditCard_PaymentFeatures_Tokenization, token replaces the clear credit card data>>.

Handling explicit card data requires a strong degree of PCI DSS
compliance. If your PCI DSS compliance is not sufficient, you can use our
<<PPv2, {payment-page-v2}>>.

_Fields_

We provide detailed descriptions of all
<<CC_Fields, _credit card_ fields>>.

_Sample_

.Request Header
[source,subs=attributes+]
----
Authorization: Basic RUVVc2VyOjFSRFhOWmtZR20=
Content-Type: application/xml
----


.XML purchase Request (Successful)
[source,xml,subs=attributes+]
----
include::{root}/samples/xml/NOVA/nova_CC_purchase_request_success.xml[]
----


*Response*

_Fields_

We provide detailed descriptions of all
<<CC_Fields, _credit card_ fields>>.

NOTE: ``<card-token>`` data replaces the ``<card>`` data in the initial response
when using the credit card for the first time.

_Sample_

.XML purchase Response (Successful)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/NOVA/nova_CC_purchase_response_success.xml[]
----


[#CreditCard_TransactionTypes_Purchase_SendingData_PurchaseUsingToken]
.purchase Using a Token

*Request*

If the credit card is already known to the merchant, a token already
exists and can be used from the beginning.

Read how a
<<CreditCard_PaymentFeatures_Tokenization, token replaces the clear credit card data>>.

_Fields_

We provide detailed descriptions of all
<<CC_Fields, _credit card_ fields>>.

_Sample_

.Request Header

[source,subs=attributes+]
----
Authorization: Basic RUVVc2VyOjFSRFhOWmtZR20=
Content-Type: application/xml
----


.XML purchase with token Request (Successful)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/NOVA/nova_CC_purchaseWithToken_request_success.xml[]
----


*Response*

_Fields_

We provide detailed descriptions of all
<<CC_Fields, _credit card_ fields>>.

_Sample_

.XML purchase with token Response (Successful)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/NOVA/nova_CC_purchaseWithToken_response_success.xml[]
----


A successful purchase response can be followed by

- a <<CreditCard_TransactionTypes_Purchase_SendingData_VoidPurchase, _void-purchase_>> (details see <<CreditCard_TransactionTypes_VoidRefund_Void, void>>).
- a <<CreditCard_TransactionTypes_Purchase_SendingData_RefundPurchase, _refund-purchase_>> (details see <<CreditCard_TransactionTypes_VoidRefund_Refund, refund>>).

//-


[#CreditCard_TransactionTypes_Purchase_SendingData_ReferencingPurchaseTransactions_Workflow]
_Workflow_

image::images/diagrams/cc_purchase-referencing.svg[ReferencingPurchaseTransactions_Workflow]

// [#CreditCard_TransactionTypes_Purchase_SendingData_ReferencingPurchaseTransactions_PurchaseRequestFirst]
// *purchase Request (recurring/first)*

// _Fields_

// We provide detailed descriptions of all
// <<CC_Fields, _credit card_ fields>>.

// _Sample_

// .Request Header
// [source,subs=attributes+]
// ----
// Authorization: Basic RUVVc2VyOjFSRFhOWmtZR20=
// Content-Type: application/xml
// ----

// .XML (recurring/first) purchase Request (Success)
// [source,xml,subs=attributes+]
// ----
// include::{root}/samples/xml/creditcard_purchase_request_success_recurring_first.xml[]
// ----

// [#CreditCard_TransactionTypes_Purchase_SendingData_ReferencingPurchaseTransactions_PurchaseResponseFirst]
// *purchase Response (recurring/first)*

// _Fields_

// We provide detailed descriptions of all
// <<CC_Fields, _credit card_ fields>>.

// _Sample_

// .XML (recurring/first) purchase Response (Success)
// [source,xml,subs=attributes+]
// ----
// include::{root}/samples/xml/creditcard_purchase_response_success_recurring_first.xml[]
// ----


[#CreditCard_TransactionTypes_Purchase_SendingData_VoidPurchase]
.void-purchase

A void-purchase must reference a successful
<<CreditCard_TransactionTypes_Purchase_SendingData_PurchaseUsingToken, purchase response>>.

NOTE: A void-purchase shall be used only, if the payment was processed in an
online shop and not at a POS.

We only list field descriptions for requests and responses. Notifications follow
the general structure described in
<<GeneralPlatformFeatures_IPN_NotificationExamples, General Platform Features>>.

*Request*

_Fields_

We provide detailed descriptions of all
<<CC_Fields, _credit card_ fields>>.

_Sample_

.Request Header

[source,subs=attributes+]
----
Authorization: Basic RUVVc2VyOjFSRFhOWmtZR20=
Content-Type: application/xml
----


.XML void-purchase Request (Successful)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/NOVA/nova_CC_voidPurchase_request_success.xml[]
----


*Response*

_Fields_

We provide detailed descriptions of all
<<CC_Fields, _credit card_ fields>>.

_Sample_

.XML void-purchase Response (Successful)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/NOVA/nova_CC_voidPurchase_response_success.xml[]
----


[#CreditCard_TransactionTypes_Purchase_SendingData_RefundPurchase]
.refund-purchase

Merchants use a refund-purchase to refund a purchase or parts of it
after the funds transfer was initiated.

A refund-purchase must reference a successful <<CreditCard_TransactionTypes_Purchase_SendingData_PurchaseUsingToken, purchase response>>.

We only list field descriptions for requests and responses. Notifications follow the general structure described in <<GeneralPlatformFeatures_IPN_NotificationExamples, General Platform Features>>.


*Request*

_Fields_

We provide detailed descriptions of all
<<CC_Fields, _credit card_ fields>>.

_Sample_

.Request Header

[source,subs=attributes+]
----
Authorization: Basic RUVVc2VyOjFSRFhOWmtZR20=
Content-Type: application/xml
----


.XML refund-purchase Request (Successful)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/NOVA/nova_CC_refundPurchase_request_success.xml[]
----


*Response*

_Fields_

We provide detailed descriptions of all
<<CC_Fields, _credit card_ fields>>.

_Sample_

.XML refund-purchase Response (Successful)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/creditcard_refund-purchase_response_success.xml[]
----


A successful refund-purchase response can be followed by a void-refund-purchase (details see
<<CreditCard_TransactionTypes_VoidRefund_Void, void>>).

[#CreditCard_TransactionTypes_Purchase_SendingData_VoidRefundPurchase]
.void-refund-purchase

With this transaction type you can void a successful refund-purchase
until the funds transfer has been triggered.

*Request*

_Fields_

We provide detailed descriptions of all
<<CC_Fields, _credit card_ fields>>.

_Sample_

.Request Header
[source,subs=attributes+]
----
Authorization: Basic RUVVc2VyOjFSRFhOWmtZR20=
Content-Type: application/xml
----


.XML void-refund-purchase Request (Successful)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/NOVA/nova_CC_voidRefundPurchase_request_success.xml[]
----


*Response*

_Fields_

We provide detailed descriptions of all <<CC_Fields, _credit card_ fields>>.

_Sample_

.XML void-refund-purchase Response (Successful)

[source,xml,subs=attributes+]
----
include::{root}/samples/xml/NOVA/nova_CC_voidRefundPurchase_response_success.xml[]
----

//-