[#PaymentPageSolutions]
== Payment Page Solutions
Our payment page solutions maximize the user experience of the checkout
process by giving you control over its design and feel. With three
readily available integration options, you decide where and how you want
your customers to pay, while still enjoying the benefits of a dependable
payment solution. All you need to get started is PCI SAQ A compliance.

_{payment-page-v2}_ delivers a highly customizable, secure and
polished checkout experience with multiple integration options. If
visual design is your main priority, _{payment-page-v2}_ gives you all
the tools you need to create a great-looking payment page.

_{payment-page-v2}_ offers:

* Credit Card support.
* support of various alternative payment methods.
* the integration types Hosted/Embedded/Seamless.
* multi-language support.
* custom CSS.
* ready-to-use integration code in Java/PHP.
* customization through GUI designer.
* multiple themes.
* responsive design (mobile & desktop).

//-

